services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  shortener:
    image: ghcr.io/romch007/url-shortener
    ports:
      - 8080:8080
    environment:
      REDIS_URL: "redis://redis/"
